import React,{useEffect,useState} from "react";
import {AlertTriangle,Archive,DatabaseBackup,RefreshCw,RotateCcw,ShieldCheck} from "lucide-react";
import {platformApi} from "./api";
import {useLanguage} from "./LanguageContext.jsx";

const messageOf=e=>e.response?.data?.message||"Backup request failed.";
const bytes=value=>!Number.isFinite(value)||value<=0?"—":value<1024?`${value} B`:value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(2)} MB`;
export default function BackupRecoveryPanel(){
 const {language,t}=useLanguage();
 const local=value=>value?new Date(value).toLocaleString(language==="hi"?"hi-IN":"en-IN"):t("Not recorded");
 const [data,setData]=useState(null),[password,setPassword]=useState(""),[selected,setSelected]=useState(null),[restore,setRestore]=useState({confirmation:"",password:""}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const {data:result}=await platformApi.get("/platform/backup-recovery");setData(result);};
 useEffect(()=>{load().catch(e=>setError(messageOf(e)));},[]);
 useEffect(()=>{if(!data?.running&&!data?.drills?.some(item=>["queued","running"].includes(item.status)))return;const timer=setInterval(()=>load().catch(()=>{}),10000);return()=>clearInterval(timer);},[data?.running,data?.drills]);
 const create=async e=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{const {data:result}=await platformApi.post("/platform/backup-recovery/backups",{password});setMessage(result.message);setPassword("");await load();}catch(e){setError(messageOf(e));}finally{setBusy(false);}};
 const startRestore=async e=>{e.preventDefault();if(!selected)return;setBusy(true);setError("");setMessage("");try{const {data:result}=await platformApi.post(`/platform/backup-recovery/backups/${selected._id}/restore-drills`,restore);setMessage(`${result.message} Target: ${result.targetDatabase}`);setSelected(null);setRestore({confirmation:"",password:""});await load();}catch(e){setError(messageOf(e));}finally{setBusy(false);}};
 if(!data)return <section className="card"><p>{t("Loading backup status…")}</p>{error&&<p className="login-error">{t(error)}</p>}</section>;
 return <section className="card backup-recovery-panel">
  <div className="card-title"><DatabaseBackup/><h2>{t("Backup & disaster recovery")}</h2></div>
  <p className="muted">{t("Backups are encrypted before leaving the server. Restore drills can target only the separately configured disposable database; production restore is intentionally unavailable from the web UI.")}</p>
  <div className="backup-kpis"><div><span>{t("Configuration")}</span><strong>{t(data.configured?"Ready":"Action required")}</strong></div><div><span>{t("Latest successful backup")}</span><strong>{local(data.latestSuccessfulAt)}</strong></div><div><span>{t("Backup health")}</span><strong className={data.healthy?"backup-good":"backup-bad"}>{t(data.healthy?"Current":"Stale / missing")}</strong></div><div><span>{t("Schedule")}</span><strong>{data.scheduleEnabled?`${t("Daily")} · ${String(data.scheduleHourUtc).padStart(2,"0")}:00 UTC`:t("Disabled")}</strong></div></div>
  {!data.configured&&<p className="login-error" role="alert"><AlertTriangle size={16}/> {t(data.configurationError)}</p>}
  <p className="muted">{t("Automatic expired-object deletion:")} {t(data.retentionDeletionEnabled?"Enabled":"Disabled (safe default)")}. {t("Production restore: disabled.")}</p>
  <form className="incident-inline" onSubmit={create}><input required type="password" autoComplete="current-password" placeholder={t("Fresh platform password")} value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary" disabled={busy||!data.configured||Boolean(data.running)}><Archive size={16}/> {t(data.running?"Backup running":"Create encrypted backup")}</button><button type="button" className="ghost" onClick={()=>load().catch(e=>setError(messageOf(e)))}><RefreshCw size={15}/> {t("Refresh")}</button></form>
  <h3>{t("Backup history")}</h3><div className="backup-table-wrap"><table className="backup-table"><thead><tr><th>{t("Created")}</th><th>{t("Trigger")}</th><th>{t("Status")}</th><th>{t("Retention")}</th><th>{t("Size")}</th><th>{t("Integrity")}</th><th>{t("Action")}</th></tr></thead><tbody>{data.backups.map(item=><tr key={item._id}><td>{local(item.createdAt)}</td><td>{t(item.trigger)}</td><td><span className={`privacy-status backup-${item.status}`}>{t(item.status)}</span>{item.failureCode&&<small>{item.failureCode}</small>}</td><td>{t(item.retentionClass)}<small>{t("Until")} {local(item.expiresAt)}</small></td><td>{bytes(item.bytes)}</td><td>{item.archiveSha256?<code title={item.archiveSha256}>{item.archiveSha256.slice(0,12)}…</code>:"—"}</td><td>{item.status==="succeeded"?<button type="button" className="ghost" onClick={()=>{setSelected(item);setRestore({confirmation:"",password:""});}}><RotateCcw size={14}/> {t("Restore drill")}</button>:"—"}</td></tr>)}</tbody></table></div>
  {!data.backups.length&&<p className="muted">{t("No backup record exists yet.")}</p>}
  {selected&&<form className="privacy-form backup-restore-form" onSubmit={startRestore}><h3><ShieldCheck size={17}/> {t("Start disposable restore drill")}</h3><p className="muted">{t("This verifies download, encryption, checksum, collection counts and transaction support. It never overwrites production. The disposable restored database must be reviewed and removed separately after testing.")}</p><label>{t("Confirmation phrase")}<code className="backup-confirmation-hint">RESTORE TO DISPOSABLE DATABASE</code><input required name="restore-confirmation" autoComplete="off" spellCheck={false} value={restore.confirmation} onChange={e=>setRestore({...restore,confirmation:e.target.value})} placeholder="RESTORE TO DISPOSABLE DATABASE"/></label><label>{t("Fresh platform password")}<input required type="password" value={restore.password} onChange={e=>setRestore({...restore,password:e.target.value})}/></label><div className="privacy-actions"><button type="button" className="ghost" onClick={()=>setSelected(null)}>{t("Cancel")}</button><button className="primary" disabled={busy||restore.confirmation!=="RESTORE TO DISPOSABLE DATABASE"}>{t("Run safe restore drill")}</button></div></form>}
  <h3>{t("Restore drill history")}</h3><div className="privacy-history">{data.drills.map(item=><article className="privacy-request" key={item._id}><div><strong>{item.targetDatabase}</strong><span className={`privacy-status backup-${item.status}`}>{t(item.status)}</span></div><small>{t("Started:")} {local(item.startedAt)} · {t("Completed:")} {local(item.completedAt)}</small>{item.status==="succeeded"&&<p>{item.collectionCount} {t("collections")} · {t("Transaction rollback verified:")} {t(item.transactionRollbackVerified?"Yes":"No")}</p>}{item.failureCode&&<p className="muted">{t("Diagnostic:")} {item.failureCode}</p>}</article>)}</div>
  {error&&<p className="login-error" role="alert">{t(error)}</p>}{message&&<p className="success" role="status">{t(message)}</p>}
 </section>;
}
