import React, { useEffect, useState } from "react";
import { ShieldCheck, RefreshCw } from "lucide-react";
import { patientPlatformApi } from "./api";
import { useLanguage } from "./LanguageContext";
const msg = error => error.response?.data?.message || "The request could not be completed.";
const label = (hi,en,hindi) => hi ? hindi : en;

export function PrivacyGuardianControls() {
 const { language, t }=useLanguage(); const hi=language==="hi";
 const [cases,setCases]=useState([]),[form,setForm]=useState({guardianName:"",guardianEmail:"",relationship:"parent"}),[otp,setOtp]=useState(""),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const {data}=await patientPlatformApi.get("/privacy/guardians");setCases(data.cases||[]);};
 useEffect(()=>{load().catch(()=>setError(t("Unable to load guardian requests.")));},[]);
 const send=async e=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{const {data}=await patientPlatformApi.post("/privacy/guardians",form);setSelected(data.id);setMessage(t(data.message));await load();}catch(e){setError(t(msg(e)));}finally{setBusy(false);}};
 const verify=async e=>{e.preventDefault();setBusy(true);setError("");try{const {data}=await patientPlatformApi.post(`/privacy/guardians/${selected}/verify`,{otp});setMessage(t(data.message));setSelected(null);setOtp("");await load();}catch(e){setError(t(msg(e)));}finally{setBusy(false);}};
 const revoke=async id=>{if(!window.confirm(t("Revoke this guardian verification record?")))return;setBusy(true);setError("");try{await patientPlatformApi.post(`/privacy/guardians/${id}/revoke`);setMessage(t("Guardian verification revoked."));await load();}catch(e){setError(t(msg(e)));}finally{setBusy(false);}};
 return <section className="card privacy-section"><div className="card-title"><ShieldCheck/><h2>{label(hi,"Guardian identity verification","अभिभावक पहचान सत्यापन")}</h2></div>
 <p className="muted">{label(hi,"For a recorded minor, verify a guardian's email and request clinic review of parental or legal authority. This does not grant another person access to medical records or enable external AI. Do not upload identity documents here.","नाबालिग के लिए अभिभावक का ईमेल सत्यापित करें और क्लिनिक से कानूनी अधिकार की जाँच कराएँ। इससे किसी अन्य व्यक्ति को मेडिकल रिकॉर्ड या बाहरी AI की पहुँच नहीं मिलती। यहाँ पहचान दस्तावेज़ अपलोड न करें।")}</p>
 <form className="privacy-form" onSubmit={send}><label>{label(hi,"Guardian name","अभिभावक का नाम")}<input required maxLength={120} minLength={2} value={form.guardianName} onChange={e=>setForm({...form,guardianName:e.target.value})}/></label><label>{label(hi,"Guardian email","अभिभावक का ईमेल")}<input type="email" required maxLength={200} value={form.guardianEmail} onChange={e=>setForm({...form,guardianEmail:e.target.value})}/></label><label>{label(hi,"Relationship","संबंध")}<select value={form.relationship} onChange={e=>setForm({...form,relationship:e.target.value})}><option value="parent">{label(hi,"Parent","माता-पिता")}</option><option value="legal_guardian">{label(hi,"Legal guardian","कानूनी अभिभावक")}</option><option value="other">{label(hi,"Other","अन्य")}</option></select></label><button className="primary" disabled={busy}>{label(hi,"Send guardian verification","अभिभावक सत्यापन भेजें")}</button></form>
 {selected&&<form className="privacy-form" onSubmit={verify}><p className="muted">{label(hi,"Enter the code sent to the guardian. It expires in five minutes.","अभिभावक को भेजा गया कोड दर्ज करें। यह पाँच मिनट में समाप्त हो जाएगा।")}</p><input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))}/><div className="privacy-actions"><button type="button" className="ghost" onClick={()=>{setSelected(null);setOtp("");}}>{label(hi,"Cancel","रद्द करें")}</button><button className="primary" disabled={busy||otp.length!==6}>{label(hi,"Verify email","ईमेल सत्यापित करें")}</button></div></form>}
 <div className="privacy-history">{cases.map(c=><article className="privacy-request" key={c.id}><strong>{c.guardianName}</strong><p>{c.guardianEmail} · {t(c.relationship.replaceAll("_"," "))}</p><small>{t(c.status.replaceAll("_"," "))}</small>{c.reviewNote&&<p className="muted">{c.reviewNote}</p>}{c.status==="pending_email"&&<><button className="ghost" onClick={()=>setSelected(c.id)}>{label(hi,"Enter verification code","सत्यापन कोड दर्ज करें")}</button><p className="muted">{label(hi,"If the code expires, request a new code using the form above after five minutes.","यदि कोड समाप्त हो जाए, तो पाँच मिनट बाद ऊपर दिए गए फॉर्म से नया कोड माँगें।")}</p><button className="ghost" disabled={busy} onClick={()=>revoke(c.id)}>{label(hi,"Cancel verification","सत्यापन रद्द करें")}</button></>}{["verified","awaiting_clinic_review"].includes(c.status)&&<button className="ghost" disabled={busy} onClick={()=>revoke(c.id)}>{label(hi,"Revoke verification","सत्यापन वापस लें")}</button>}</article>)}</div>
 {error&&<p className="login-error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
 </section>;
}

export function PrivacyCorrectionControls({onCreated}) {
 const {language,t}=useLanguage();const hi=language==="hi";
 const [form,setForm]=useState({scope:"global_profile",field:"name",recordId:"",clinicSlug:"",proposedValue:"",reason:""}),[otp,setOtp]=useState(""),[stage,setStage]=useState("compose"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const update=(key,value)=>setForm(v=>({...v,[key]:value}));
 const send=async e=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{await patientPlatformApi.post("/privacy/verification",{type:"correction"});setStage("verify");setMessage(t("A fresh code was sent to your registered email."));}catch(e){setError(t(msg(e)));}finally{setBusy(false);}};
 const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{const {data}=await patientPlatformApi.post("/privacy/corrections",{...form,otp});setMessage(t(data.message));setStage("compose");setOtp("");setForm({...form,proposedValue:"",reason:""});if(onCreated)await onCreated();}catch(e){setError(t(msg(e)));}finally{setBusy(false);}};
 return <section className="card privacy-section"><div className="card-title"><ShieldCheck/><h2>{label(hi,"Request a data correction","डेटा सुधार का अनुरोध")}</h2></div><p className="muted">{label(hi,"Describe the record and requested change. Clinical corrections are reviewed by the responsible clinic and are never silently rewritten. You can still edit your own reusable profile through the existing profile page.","रिकॉर्ड और इच्छित सुधार बताएं। क्लिनिकल सुधार संबंधित क्लिनिक की समीक्षा के बाद ही होंगे। आप मौजूदा प्रोफ़ाइल पेज से अपनी साझा प्रोफ़ाइल बदल सकते हैं।")}</p>
 <form className="privacy-form" onSubmit={stage==="verify"?submit:send}><label>{label(hi,"Record scope","रिकॉर्ड का दायरा")}<select disabled={stage==="verify"||busy} value={form.scope} onChange={e=>update("scope",e.target.value)}><option value="global_profile">{label(hi,"Global profile","साझा प्रोफ़ाइल")}</option><option value="clinic_record">{label(hi,"Clinic record","क्लिनिक रिकॉर्ड")}</option></select></label><label>{label(hi,"Field","फ़ील्ड")} {form.scope==="global_profile"?<select disabled={stage==="verify"||busy} value={form.field} onChange={e=>update("field",e.target.value)}>{["name","phone","dateOfBirth","gender","bloodGroup","allergies","medicalHistory","currentMedications","pastSurgeries","emergencyContact.name","emergencyContact.phone"].map(x=><option key={x}>{t(x)}</option>)}</select>:<input required maxLength={100} disabled={stage==="verify"||busy} value={form.field} onChange={e=>update("field",e.target.value)}/>}</label>
 {form.scope==="clinic_record"&&<><label>{label(hi,"Clinic slug","क्लिनिक स्लग")}<input required maxLength={80} disabled={stage==="verify"||busy} value={form.clinicSlug} onChange={e=>update("clinicSlug",e.target.value)}/></label><label>{label(hi,"Record reference","रिकॉर्ड संदर्भ")}<input required maxLength={80} disabled={stage==="verify"||busy} value={form.recordId} onChange={e=>update("recordId",e.target.value)}/></label></>}
 <label>{label(hi,"Requested correct value","अनुरोधित सही मान")}<textarea required rows={2} maxLength={1000} disabled={stage==="verify"||busy} value={form.proposedValue} onChange={e=>update("proposedValue",e.target.value)}/></label><label>{label(hi,"Reason for correction","सुधार का कारण")}<textarea required minLength={10} maxLength={1000} rows={2} disabled={stage==="verify"||busy} value={form.reason} onChange={e=>update("reason",e.target.value)}/></label>
 {stage==="verify"&&<label>{label(hi,"Email verification code","ईमेल सत्यापन कोड")}<input required pattern="[0-9]{6}" inputMode="numeric" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))}/></label>}
 <div className="privacy-actions">{stage==="verify"&&<button type="button" className="ghost" onClick={()=>{setStage("compose");setOtp("");}}>{label(hi,"Back","वापस")}</button>}<button className="primary" disabled={busy||(stage==="verify"&&otp.length!==6)}>{label(hi,stage==="verify"?"Verify & submit":"Send verification code",stage==="verify"?"सत्यापित करके जमा करें":"सत्यापन कोड भेजें")}</button></div></form>{error&&<p className="login-error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}</section>;
}
