export const POLICY_VERSION = '2026-09-09';
export const SUPPORT_EMAIL = 'rishabhmishra263800@gmail.com';
export const publicNavigation = [
  ['/faqs', 'FAQs', 'अक्सर पूछे जाने वाले प्रश्न'],
  ['/privacy', 'Privacy Policy', 'गोपनीयता नीति'],
  ['/terms', 'Terms & Conditions', 'नियम और शर्तें'],
  ['/support', 'Contact / Support', 'संपर्क / सहायता'],
];
// Each row is [English title, Hindi title, English body, Hindi body].
export const publicContent = {
  faqs: {
    title: ['A little help, before your visit.', 'आपकी अगली विज़िट के लिए थोड़ी मदद।'],
    intro: ['Answers for patients, doctors and clinic teams using OPDfy.', 'OPDfy का उपयोग करने वाले मरीज़ों, डॉक्टरों और क्लिनिक टीम के लिए जानकारी।'],
    sections: [
      ['How do I book a token?', 'टोकन कैसे बुक करें?', 'Sign in to the patient portal using the code sent to your email. Choose an available clinic, complete your patient details, then select a department and doctor. Confirm the booking and follow your live token status.', 'ईमेल पर आए कोड से मरीज़ पोर्टल में प्रवेश करें। उपलब्ध क्लिनिक चुनें, मरीज़ की जानकारी भरें और विभाग तथा डॉक्टर चुनें। बुकिंग की पुष्टि के बाद टोकन की लाइव स्थिति देखें।'],
      ['Can I visit without a smartphone?', 'क्या स्मार्टफ़ोन के बिना आ सकते हैं?', 'Yes. Ask the clinic reception to register a walk-in visit and issue a token. The clinic can help you with a printed token slip and its waiting-room display.', 'हाँ। क्लिनिक के रिसेप्शन से पंजीकरण और टोकन के लिए कहें। क्लिनिक आपको प्रिंटेड टोकन पर्ची और प्रतीक्षालय डिस्प्ले की मदद दे सकता है।'],
      ['Is the waiting time guaranteed?', 'क्या प्रतीक्षा समय निश्चित होता है?', 'No. Estimates can change with consultation duration, doctor breaks, emergencies and queue adjustments. Follow the current status and instructions from reception.', 'नहीं। परामर्श में लगने वाले समय, डॉक्टर के विराम, आपात मामलों और कतार में बदलाव से अनुमान बदल सकता है। वर्तमान स्थिति और रिसेप्शन के निर्देश देखें।'],
      ['What should I do in an emergency?', 'आपात स्थिति में क्या करें?', 'Do not wait for an online token or a support reply. Seek immediate in-person medical help or contact your local emergency service. An emergency booking label is not an emergency response service; clinic staff assess priority.', 'ऑनलाइन टोकन या सहायता के जवाब का इंतज़ार न करें। तुरंत नज़दीकी चिकित्सा सहायता या स्थानीय आपात सेवा से संपर्क करें। बुकिंग का आपात लेबल आपात सेवा नहीं है; प्राथमिकता क्लिनिक का स्टाफ तय करता है।'],
      ['How do I cancel or change a booking?', 'बुकिंग रद्द या बदलें कैसे?', 'Use the available cancellation action in your patient dashboard. Available actions depend on the booking status. Contact reception for a transfer, missed call, rescheduling or a booking that can no longer be cancelled online.', 'मरीज़ डैशबोर्ड में उपलब्ध रद्द करने का विकल्प उपयोग करें। विकल्प बुकिंग की स्थिति पर निर्भर हैं। विभाग बदलने, कॉल छूटने, समय बदलने या ऑनलाइन रद्द न हो पाने पर रिसेप्शन से संपर्क करें।'],
      ['What do doctor ratings mean?', 'डॉक्टर की रेटिंग का क्या अर्थ है?', 'Displayed ratings summarize feedback linked to eligible completed visits, with the review count where available. A new doctor may have no verified rating. Reviews reflect patient experiences and are not a guarantee of clinical outcomes.', 'दिखाई गई रेटिंग योग्य पूरी हो चुकी विज़िट से जुड़े फ़ीडबैक का सार है; उपलब्ध होने पर समीक्षा संख्या भी दिखती है। नए डॉक्टर की सत्यापित रेटिंग नहीं हो सकती। समीक्षाएँ अनुभव बताती हैं, इलाज के परिणाम की गारंटी नहीं।'],
      ['Where are prescriptions and referrals?', 'प्रिस्क्रिप्शन और रेफ़रल कहाँ मिलेंगे?', 'Open your clinic dashboard and visit history to see records made available to you. Doctors can create department referrals within the same clinic; their status is shown in the referral section. Ask the clinic about a missing prescription or referral.', 'क्लिनिक डैशबोर्ड और विज़िट इतिहास में उपलब्ध रिकॉर्ड देखें। डॉक्टर उसी क्लिनिक के दूसरे विभाग में रेफ़रल दे सकते हैं; उसकी स्थिति रेफ़रल सेक्शन में दिखती है। रिकॉर्ड न मिलने पर क्लिनिक से संपर्क करें।'],
      ['Can every clinic see my medical records?', 'क्या हर क्लिनिक मेरे चिकित्सा रिकॉर्ड देख सकता है?', 'Your global patient account supports access across clinics, while clinical visit records are scoped to the clinic providing care. Authorized staff at that clinic access records according to their role. Review the Privacy Policy for shared account information and service processing.', 'आपका साझा मरीज़ खाता कई क्लिनिक में प्रवेश देता है, लेकिन इलाज की विज़िट के रिकॉर्ड संबंधित क्लिनिक के दायरे में रहते हैं। उस क्लिनिक के अधिकृत स्टाफ को उनकी भूमिका के अनुसार पहुँच मिलती है। साझा खाता जानकारी और सेवा में डेटा उपयोग के लिए गोपनीयता नीति पढ़ें।'],
      ['My email code did not arrive. What next?', 'ईमेल कोड नहीं आया, अब क्या करें?', 'Check the entered email and your spam folder. Use Resend Code when available; avoid repeated requests. Never share a code with anyone. If delivery still fails, contact support without sending your password or code.', 'ईमेल पता और स्पैम फ़ोल्डर जाँचें। विकल्प उपलब्ध होने पर कोड दोबारा भेजें और बार-बार अनुरोध न करें। कोड किसी को न दें। समस्या बनी रहे तो सहायता से संपर्क करें, लेकिन पासवर्ड या कोड न भेजें।'],
      ['How do staff reset a forgotten password?', 'स्टाफ भूला हुआ पासवर्ड कैसे बदले?', 'On Staff Sign In, select the clinic and choose Forgot password. Use the email registered for your admin, doctor or receptionist account. The verification code goes to that registered address. Contact the clinic administrator if your registered email is wrong.', 'स्टाफ प्रवेश पर क्लिनिक चुनकर पासवर्ड भूल गए विकल्प चुनें। एडमिन, डॉक्टर या रिसेप्शनिस्ट खाते का पंजीकृत ईमेल दें। सत्यापन कोड उसी पते पर जाएगा। ईमेल गलत होने पर क्लिनिक एडमिन से संपर्क करें।'],
      ['When does a newly registered clinic become available?', 'नया पंजीकृत क्लिनिक कब उपलब्ध होता है?', 'Clinic registration is reviewed by the platform administrator. Submitting a request does not immediately activate the workspace. Approval, subscription status and any suspension affect availability. Contact support for registration questions.', 'क्लिनिक पंजीकरण की समीक्षा प्लेटफ़ॉर्म एडमिन करता है। अनुरोध भेजते ही कार्यक्षेत्र सक्रिय नहीं होता। मंज़ूरी, सदस्यता की स्थिति और निलंबन से उपलब्धता प्रभावित होती है। पंजीकरण संबंधी सवालों के लिए सहायता से संपर्क करें।'],
      ['Who handles fees, refunds and medical questions?', 'शुल्क, वापसी और चिकित्सा सवाल कौन संभालता है?', 'The treating clinic sets consultation charges and handles payment or refund questions. OPDfy records clinic workflows and does not replace the treating doctor. Contact your clinic for treatment, prescriptions and clinical advice.', 'इलाज करने वाला क्लिनिक परामर्श शुल्क तय करता है और भुगतान या वापसी संबंधी सवाल संभालता है। OPDfy क्लिनिक के काम का रिकॉर्ड रखता है और डॉक्टर का विकल्प नहीं है। इलाज, प्रिस्क्रिप्शन और चिकित्सा सलाह के लिए अपने क्लिनिक से संपर्क करें।'],
      ['How do I change language or appearance?', 'भाषा या थीम कैसे बदलें?', 'Use the language selector and light/dark button in the header. Hindi and English change interface labels; patient names, staff details, token numbers and clinical text stay as entered. Preferences are saved in this browser.', 'ऊपर दिए भाषा चयन और लाइट/डार्क बटन का उपयोग करें। हिंदी और अंग्रेज़ी से इंटरफ़ेस के शब्द बदलते हैं; नाम, स्टाफ की जानकारी, टोकन संख्या और चिकित्सा विवरण मूल रूप में रहते हैं। पसंद इसी ब्राउज़र में सहेजी जाती है।'],
    ],
  },
  privacy: {
    title: ['Your information, explained clearly.', 'आपकी जानकारी का उपयोग, स्पष्ट शब्दों में।'],
    intro: ['This notice explains how OPDfy handles information in patient accounts and clinic workspaces. For questions or privacy requests, use the contact below.', 'यह सूचना बताती है कि OPDfy मरीज़ खातों और क्लिनिक कार्यक्षेत्र में जानकारी कैसे संभालता है। सवाल या गोपनीयता अनुरोध के लिए नीचे दिए संपर्क का उपयोग करें।'],
    sections: [
      ['1. Who to contact', '1. किससे संपर्क करें', 'OPDfy provides the platform. Your treating clinic manages the care it delivers and the clinical records its team enters. Send platform privacy questions to the support email below; contact the treating clinic for corrections to its medical records. We may need to verify your identity and coordinate with that clinic.', 'OPDfy प्लेटफ़ॉर्म उपलब्ध कराता है। आपका क्लिनिक अपने इलाज और अपनी टीम द्वारा दर्ज चिकित्सा रिकॉर्ड का प्रबंधन करता है। प्लेटफ़ॉर्म की गोपनीयता के सवाल नीचे दिए ईमेल पर और चिकित्सा रिकॉर्ड में सुधार के लिए संबंधित क्लिनिक को भेजें। पहचान सत्यापन और क्लिनिक से समन्वय की आवश्यकता हो सकती है।'],
      ['2. Information used by the service', '2. सेवा में उपयोग होने वाली जानकारी', 'Depending on the features you use, records can include names, email addresses, phone numbers, demographic and profile information, clinic and staff details, appointments, tokens, symptoms, medical history, consultations, prescriptions, referrals, visit feedback and payment-status entries. Authentication, request and activity records may contain timestamps, account identifiers, IP addresses and device/request information for security and operations.', 'उपयोग की गई सुविधाओं के अनुसार नाम, ईमेल, फ़ोन, व्यक्तिगत और प्रोफ़ाइल जानकारी, क्लिनिक व स्टाफ विवरण, अपॉइंटमेंट, टोकन, लक्षण, चिकित्सा इतिहास, परामर्श, प्रिस्क्रिप्शन, रेफ़रल, फ़ीडबैक और भुगतान की स्थिति दर्ज हो सकती है। सुरक्षा और संचालन के लिए प्रवेश व गतिविधि रिकॉर्ड में समय, खाता पहचान, IP पता और डिवाइस/अनुरोध संबंधी जानकारी हो सकती है।'],
      ['3. Why information is processed', '3. जानकारी का उपयोग क्यों होता है', 'Information supports account verification, clinic registration, booking and queue operations, care documentation, referrals, email codes, service support, clinic reports and protection against misuse. Provide information relevant to your visit; do not enter someone else’s details unless you are authorized to act for them.', 'जानकारी का उपयोग खाता सत्यापन, क्लिनिक पंजीकरण, बुकिंग, कतार संचालन, इलाज का रिकॉर्ड, रेफ़रल, ईमेल कोड, सहायता, क्लिनिक रिपोर्ट और दुरुपयोग से बचाव में होता है। विज़िट से संबंधित जानकारी दें; किसी और की जानकारी तभी दर्ज करें जब आपको उनकी ओर से काम करने का अधिकार हो।'],
      ['4. Clinic access and shared account information', '4. क्लिनिक की पहुँच और साझा खाता जानकारी', 'A global patient account lets you choose among clinics. Account/profile information needed to register with a selected clinic can be used there; visit records are scoped to the clinic where care is delivered. Role-based access limits clinic staff actions. Authorized platform operations and service providers may process information as needed to operate, support and protect the service; clinic isolation does not mean the platform has no technical access.', 'साझा मरीज़ खाता आपको क्लिनिक चुनने देता है। चुने गए क्लिनिक में पंजीकरण के लिए आवश्यक खाता/प्रोफ़ाइल जानकारी वहाँ उपयोग हो सकती है; विज़िट रिकॉर्ड इलाज वाले क्लिनिक के दायरे में रहता है। स्टाफ की भूमिका के अनुसार पहुँच सीमित होती है। अधिकृत प्लेटफ़ॉर्म संचालन और सेवा प्रदाता संचालन, सहायता व सुरक्षा के लिए जानकारी संसाधित कर सकते हैं; क्लिनिक अलगाव का अर्थ प्लेटफ़ॉर्म की तकनीकी पहुँच का पूरी तरह अभाव नहीं है।'],
      ['5. Hosting, email and optional AI', '5. होस्टिंग, ईमेल और वैकल्पिक AI', 'The deployment may use MongoDB for data storage, Render/Vercel for hosting and an email provider such as Brevo for verification messages. Actual providers and processing locations depend on the deployment; ask support for current details. If you allow external AI for a browser session, your message or symptom text may be sent to the configured provider, such as Google Gemini. You can decline and use available built-in help. Avoid sharing unnecessary identifiers in AI messages.', 'तैनाती में डेटा के लिए MongoDB, होस्टिंग के लिए Render/Vercel और सत्यापन ईमेल के लिए Brevo जैसे प्रदाता उपयोग हो सकते हैं। वास्तविक प्रदाता और डेटा संसाधन स्थान तैनाती पर निर्भर हैं; वर्तमान जानकारी सहायता से माँगें। ब्राउज़र सत्र के लिए बाहरी AI की अनुमति देने पर संदेश या लक्षण Google Gemini जैसे निर्धारित प्रदाता को भेजे जा सकते हैं। आप मना करके उपलब्ध अंतर्निहित मदद उपयोग कर सकते हैं। AI संदेशों में अनावश्यक पहचान जानकारी न दें।'],
      ['6. Browser storage', '6. ब्राउज़र में संग्रहण', 'This application uses session storage for sign-in sessions and clinic selection, and local storage for language and appearance preferences. Optional AI permission is held for the browser session. Logging out ends the relevant app session; clearing browser storage can reset preferences and sign you out. These actions do not delete clinic records held on the server.', 'ऐप प्रवेश सत्र और क्लिनिक चयन के लिए सत्र संग्रहण तथा भाषा और थीम के लिए स्थानीय संग्रहण उपयोग करता है। वैकल्पिक AI अनुमति ब्राउज़र सत्र के लिए रखी जाती है। लॉग आउट से संबंधित ऐप सत्र समाप्त होता है; ब्राउज़र संग्रहण मिटाने से पसंद रीसेट और लॉग आउट हो सकता है। इससे सर्वर पर रखे क्लिनिक रिकॉर्ड नहीं मिटते।'],
      ['7. Retention and deletion requests', '7. रिकॉर्ड रखना और हटाने के अनुरोध', 'Retention depends on the type of record, service needs and the treating clinic’s applicable medical and legal record-keeping obligations. There is no single automatic deletion period for all medical records. Request account closure or deletion through support and your clinic; retained records and any applicable restrictions will need review. Suspending a clinic or signing out does not delete its records.', 'रिकॉर्ड रखने की अवधि उसके प्रकार, सेवा की आवश्यकता और संबंधित क्लिनिक के लागू चिकित्सा व कानूनी दायित्वों पर निर्भर करती है। सभी चिकित्सा रिकॉर्ड के लिए एक समान स्वचालित हटाने की अवधि नहीं है। खाता बंद या डेटा हटाने का अनुरोध सहायता और अपने क्लिनिक को दें; रिकॉर्ड और लागू सीमाओं की समीक्षा ज़रूरी होगी। क्लिनिक निलंबित करने या लॉग आउट से रिकॉर्ड नहीं मिटते।'],
      ['8. Your choices and requests', '8. आपके विकल्प और अनुरोध', 'You can request access to your information, corrections, account closure, deletion or help with a privacy concern through support. Contact the treating clinic for clinical corrections and copies. Where processing depends on your permission, you may ask to withdraw it; some services may then be unavailable and required records may still need to be retained. We may verify identity before sharing or changing information.', 'आप सहायता के माध्यम से अपनी जानकारी की पहुँच, सुधार, खाता बंद करने, हटाने या गोपनीयता संबंधी मदद का अनुरोध कर सकते हैं। चिकित्सा सुधार और प्रतियों के लिए संबंधित क्लिनिक से संपर्क करें। अनुमति आधारित संसाधन के लिए अनुमति वापस लेने का अनुरोध कर सकते हैं; कुछ सेवाएँ तब उपलब्ध नहीं होंगी और आवश्यक रिकॉर्ड रखने पड़ सकते हैं। जानकारी देने या बदलने से पहले पहचान सत्यापन हो सकता है।'],
      ['9. Children and people acting for others', '9. बच्चे और किसी अन्य की ओर से कार्य करना', 'For a child or a person who needs help, contact the clinic about the appropriate guardian or representative process before entering their information. Do not claim authority you do not have. This platform notice does not replace the clinic’s consent for medical treatment or its guardian-verification responsibilities.', 'बच्चे या सहायता की आवश्यकता वाले व्यक्ति की जानकारी दर्ज करने से पहले क्लिनिक से उचित अभिभावक या प्रतिनिधि प्रक्रिया पूछें। जिस अधिकार के आप पात्र नहीं हैं उसका दावा न करें। यह सूचना इलाज की क्लिनिक सहमति या अभिभावक सत्यापन की ज़िम्मेदारी का विकल्प नहीं है।'],
      ['10. Protection and notice updates', '10. सुरक्षा और सूचना में बदलाव', 'The application includes authentication, role and clinic access controls and activity logging. No online system can promise absolute security. Report suspected unauthorized access promptly without sending passwords, codes or full medical documents. Material changes to this notice will be reflected in its updated version; contact support if you need clarification.', 'ऐप में प्रवेश सत्यापन, भूमिका व क्लिनिक आधारित पहुँच नियंत्रण और गतिविधि रिकॉर्ड हैं। कोई ऑनलाइन प्रणाली पूर्ण सुरक्षा का वादा नहीं कर सकती। संदिग्ध अनधिकृत पहुँच की सूचना तुरंत दें, लेकिन पासवर्ड, कोड या पूरे चिकित्सा दस्तावेज़ न भेजें। इस सूचना में महत्वपूर्ण बदलाव नए संस्करण में दिखेंगे; स्पष्टीकरण के लिए सहायता से संपर्क करें।'],
    ],
  },
  terms: {
    title: ['Clear terms for coordinated care.', 'क्लिनिक सेवा के लिए स्पष्ट नियम।'],
    intro: ['These terms describe use of OPDfy by patients and authorized clinic teams. Read them alongside the Privacy Policy.', 'ये नियम मरीज़ों और अधिकृत क्लिनिक टीम द्वारा OPDfy के उपयोग को बताते हैं। इन्हें गोपनीयता नीति के साथ पढ़ें।'],
    sections: [
      ['1. Service and acceptance', '1. सेवा और स्वीकृति', 'OPDfy supports clinic registration, queues, appointments, records and related workflows. By agreeing to these terms and using the service, you agree to use it lawfully and within your authorized role. If you do not agree, do not create an account; contact the clinic about other ways to access care.', 'OPDfy क्लिनिक पंजीकरण, कतार, अपॉइंटमेंट, रिकॉर्ड और संबंधित काम में मदद करता है। इन नियमों को स्वीकार करके सेवा उपयोग करने पर आप कानूनी रूप से और अपनी अधिकृत भूमिका के भीतर उपयोग करने के लिए सहमत हैं। सहमत न होने पर खाता न बनाएँ; इलाज के अन्य तरीकों के लिए क्लिनिक से संपर्क करें।'],
      ['2. Accounts and authority', '2. खाते और अधिकार', 'Provide accurate information and protect your password and verification codes. Use only accounts you are authorized to access. Clinic registrants must be authorized to act for the clinic. Clinic administrators are responsible for appropriate staff access and removing access when staff leave. Report suspected misuse to support.', 'सही जानकारी दें और पासवर्ड व सत्यापन कोड सुरक्षित रखें। केवल अधिकृत खाते उपयोग करें। क्लिनिक पंजीकरण करने वाले को उसकी ओर से कार्य करने का अधिकार होना चाहिए। एडमिन स्टाफ की उचित पहुँच और नौकरी छोड़ने पर पहुँच हटाने के लिए ज़िम्मेदार है। संदिग्ध दुरुपयोग की सूचना सहायता को दें।'],
      ['3. Medical responsibility and emergencies', '3. चिकित्सा ज़िम्मेदारी और आपात स्थिति', 'Clinical decisions, prescriptions, referrals and treatment remain the responsibility of the treating healthcare professionals. Queue information, reviews and AI suggestions are not a diagnosis or a substitute for professional care. The platform is not an emergency service. Seek immediate medical help in an emergency.', 'चिकित्सा निर्णय, प्रिस्क्रिप्शन, रेफ़रल और इलाज संबंधित चिकित्सा पेशेवरों की ज़िम्मेदारी हैं। कतार जानकारी, समीक्षा और AI सुझाव निदान या पेशेवर इलाज का विकल्प नहीं हैं। प्लेटफ़ॉर्म आपात सेवा नहीं है। आपात स्थिति में तुरंत चिकित्सा सहायता लें।'],
      ['4. Bookings and queue changes', '4. बुकिंग और कतार में बदलाव', 'A token or appointment supports clinic coordination and does not guarantee an exact consultation time. Staff may adjust priority, transfer, hold or reschedule visits according to clinical and operational needs. Follow clinic check-in and payment instructions; available cancellation actions depend on booking status.', 'टोकन या अपॉइंटमेंट क्लिनिक समन्वय में मदद करता है और परामर्श के निश्चित समय की गारंटी नहीं देता। स्टाफ चिकित्सा व संचालन आवश्यकताओं के अनुसार प्राथमिकता, विभाग, होल्ड या समय बदल सकता है। चेक-इन और भुगतान के क्लिनिक निर्देश मानें; रद्द करने के विकल्प बुकिंग की स्थिति पर निर्भर हैं।'],
      ['5. Fees, subscriptions and suspension', '5. शुल्क, सदस्यता और निलंबन', 'Clinics determine treatment charges and their payment/refund arrangements; ask the clinic before booking if charges are unclear. Platform subscription terms and charges must be agreed separately with the clinic. Registration requires approval, and clinic access may be restricted for expiry, suspension, security or misuse. Suspension does not itself delete records or decide any refund entitlement.', 'इलाज के शुल्क और भुगतान/वापसी व्यवस्था क्लिनिक तय करता है; शुल्क अस्पष्ट हो तो बुकिंग से पहले पूछें। प्लेटफ़ॉर्म सदस्यता के नियम और शुल्क क्लिनिक के साथ अलग तय होंगे। पंजीकरण के लिए मंज़ूरी आवश्यक है और अवधि समाप्ति, निलंबन, सुरक्षा या दुरुपयोग पर पहुँच सीमित हो सकती है। निलंबन से अपने आप रिकॉर्ड नहीं मिटते और न ही वापसी का अधिकार तय होता है।'],
      ['6. Responsible use and records', '6. ज़िम्मेदार उपयोग और रिकॉर्ड', 'Do not impersonate others, submit fraudulent reviews, abuse staff, upload harmful material, attempt unauthorized access or disrupt the service. Enter and access patient information only with the required authority. Clinics remain responsible for the accuracy of their clinical entries and for lawful handling, sharing and retention of records.', 'दूसरे की पहचान का उपयोग, फ़र्ज़ी समीक्षा, स्टाफ से दुर्व्यवहार, हानिकारक सामग्री, अनधिकृत पहुँच या सेवा में बाधा न डालें। आवश्यक अधिकार के साथ ही मरीज़ की जानकारी दर्ज या देखें। क्लिनिक अपनी चिकित्सा प्रविष्टियों की शुद्धता और रिकॉर्ड के वैध उपयोग, साझा करने व संरक्षण के लिए ज़िम्मेदार हैं।'],
      ['7. Availability and third-party services', '7. उपलब्धता और अन्य सेवा प्रदाता', 'Access can be affected by maintenance, internet connectivity, hosting or email-provider failures. Clinics should maintain an operational fallback for interruptions. External services and optional AI can have their own terms. No uninterrupted-service or clinical-outcome guarantee is provided by these terms.', 'रखरखाव, इंटरनेट, होस्टिंग या ईमेल प्रदाता की समस्या से पहुँच प्रभावित हो सकती है। क्लिनिक रुकावट के समय वैकल्पिक काम की व्यवस्था रखें। बाहरी सेवाओं और वैकल्पिक AI के अपने नियम हो सकते हैं। ये नियम लगातार उपलब्धता या इलाज के परिणाम की गारंटी नहीं देते।'],
      ['8. Ending use and responsibility for loss', '8. उपयोग समाप्त करना और नुकसान की ज़िम्मेदारी', 'You may stop using the platform and request account closure through support. Medical-record retention is handled as described in the Privacy Policy. Responsibility for any loss depends on the facts and applicable law; these terms do not exclude rights or liabilities that cannot lawfully be excluded.', 'आप प्लेटफ़ॉर्म उपयोग बंद करके सहायता से खाता बंद करने का अनुरोध कर सकते हैं। चिकित्सा रिकॉर्ड का संरक्षण गोपनीयता नीति के अनुसार संभाला जाएगा। नुकसान की ज़िम्मेदारी तथ्यों और लागू कानून पर निर्भर है; ये नियम उन अधिकारों या दायित्वों को नहीं हटाते जिन्हें कानूनी रूप से हटाया नहीं जा सकता।'],
      ['9. Questions, changes and applicable law', '9. सवाल, बदलाव और लागू कानून', 'Contact support first for platform concerns and the treating clinic for care-related disputes. Use is subject to applicable Indian law and any mandatory protections that apply to you. Updated terms carry a new version date; material changes may require fresh acceptance. The support contact below can clarify which terms apply to your service.', 'प्लेटफ़ॉर्म संबंधी सवाल पहले सहायता को और इलाज संबंधी विवाद संबंधित क्लिनिक को दें। उपयोग पर लागू भारतीय कानून और आपके अनिवार्य कानूनी संरक्षण लागू होंगे। बदले नियमों पर नई संस्करण तारीख होगी; महत्वपूर्ण बदलाव पर फिर स्वीकृति की आवश्यकता हो सकती है। नीचे दिया संपर्क आपके सेवा नियम स्पष्ट कर सकता है।'],
    ],
  },
  support: {
    title: ['We’re here to help.', 'हम आपकी मदद के लिए हैं।'],
    intro: ['For login trouble, clinic registration, technical issues or privacy requests, email OPDfy support.', 'प्रवेश की समस्या, क्लिनिक पंजीकरण, तकनीकी परेशानी या गोपनीयता अनुरोध के लिए OPDfy सहायता को ईमेल करें।'],
    sections: [
      ['What to include', 'क्या जानकारी दें', 'Include your role, clinic name or slug, the page where the issue occurred, approximate time and steps to reproduce it. You may attach a screenshot after hiding personal and medical details. Email support does not send a ticket automatically from this page; the button opens your email application.', 'अपनी भूमिका, क्लिनिक नाम या पहचान, समस्या वाला पेज, अनुमानित समय और समस्या दोहराने के चरण बताएँ। व्यक्तिगत व चिकित्सा जानकारी छिपाकर स्क्रीनशॉट दे सकते हैं। यह पेज अपने आप टिकट नहीं भेजता; बटन आपका ईमेल ऐप खोलता है।'],
      ['Keep sensitive information private', 'संवेदनशील जानकारी सुरक्षित रखें', 'Never email passwords, OTPs, access tokens, database credentials or complete medical records. Start with a brief description. If identity verification or further information is needed, support will explain the next step.', 'पासवर्ड, OTP, प्रवेश टोकन, डेटाबेस पासवर्ड या पूरे चिकित्सा रिकॉर्ड ईमेल न करें। पहले छोटा विवरण दें। पहचान सत्यापन या अधिक जानकारी की आवश्यकता होने पर सहायता अगला चरण बताएगी।'],
      ['Care and urgent help', 'इलाज और तुरंत सहायता', 'Contact the treating clinic for appointments, consultation fees, prescriptions, refunds and medical advice. This inbox is not an emergency or continuously monitored medical service. Do not wait for an email response in an emergency.', 'अपॉइंटमेंट, परामर्श शुल्क, प्रिस्क्रिप्शन, वापसी और चिकित्सा सलाह के लिए संबंधित क्लिनिक से संपर्क करें। यह ईमेल आपात या लगातार निगरानी वाली चिकित्सा सेवा नहीं है। आपात स्थिति में ईमेल के उत्तर का इंतज़ार न करें।'],
    ],
  },
};
