import mongoose from "mongoose";

const tenantSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true, maxlength: 120 },
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      match: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
      maxlength: 80,
    },
    status: {
      type: String,
      enum: ["pending", "active", "rejected", "suspended", "expired"],
      default: "pending",
      index: true,
    },
    contactEmail: { type: String, default: "", lowercase: true, trim: true },
    contactPhone: { type: String, default: "", trim: true },
    timezone: { type: String, default: "Asia/Kolkata", trim: true },
    legalVerification: {
      type: new mongoose.Schema({
        legalName: { type: String, default: "", trim: true, maxlength: 160 },
        establishmentType: { type: String, enum: ["clinic", "polyclinic", "hospital", "nursing_home", "diagnostic_centre", "other"], default: "clinic" },
        registrationNumber: { type: String, default: "", trim: true, maxlength: 100 },
        registrationAuthority: { type: String, default: "", trim: true, maxlength: 140 },
        registrationState: { type: String, default: "", trim: true, maxlength: 80 },
        certificateExpiresAt: { type: Date, default: null },
        evidenceReference: { type: String, default: "", trim: true, maxlength: 240 },
        status: { type: String, enum: ["not_submitted", "submitted", "platform_reviewed", "rejected"], default: "not_submitted" },
        submittedAt: { type: Date, default: null },
        reviewedAt: { type: Date, default: null },
        reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "SuperAdmin", default: null },
        reviewNote: { type: String, default: "", trim: true, maxlength: 1000 },
        reviewEvidenceReference: { type: String, default: "", trim: true, maxlength: 240 },
        events: { type: [{ status: String, at: Date, actorType: String, actorId: String, note: String, evidenceReference: String, _id: false }], default: [] },
      }, { _id: false }),
      default: undefined,
    },
    settings: {
      displayName: { type: String, default: "", trim: true, maxlength: 120 },
      defaultDepartment: { type: String, default: "General OPD", trim: true },
      branding: {
        shortName: { type: String, default: "", trim: true, maxlength: 40 },
        logoUrl: { type: String, default: "", trim: true, maxlength: 220000 },
        address: { type: String, default: "", trim: true, maxlength: 240 },
        website: { type: String, default: "", trim: true, maxlength: 180 },
        primaryColor: { type: String, default: "#0f766e", trim: true, maxlength: 7 },
        accentColor: { type: String, default: "#14b8a6", trim: true, maxlength: 7 },
        waitingLoungeWelcome: { type: String, default: "Welcome. Please watch the screen for your token.", trim: true, maxlength: 180 },
        footerText: { type: String, default: "", trim: true, maxlength: 240 },
      },
      billing: {
        enabled: { type: Boolean, default: true },
        currency: { type: String, enum: ["INR"], default: "INR" },
        clinicDefaultFee: { type: Number, default: 0, min: 0, max: 1000000 },
        departmentFees: {
          type: [{
            department: { type: String, required: true, trim: true },
            amount: { type: Number, required: true, min: 0, max: 1000000 },
            _id: false,
          }],
          default: [],
        },
        allowReceptionFeeOverride: { type: Boolean, default: false },
        maxDiscountPercent: { type: Number, default: 0, min: 0, max: 100 },
      },
      operations: {
        clinicHoursEnabled: { type: Boolean, default: false },
        workingDays: {
          type: [String],
          default: () => ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        },
        openTime: { type: String, default: "08:00", trim: true },
        closeTime: { type: String, default: "20:00", trim: true },
        bookingCutoffMinutes: { type: Number, default: 30, min: 0, max: 240 },
        checkInCutoffMinutes: { type: Number, default: 30, min: 0, max: 240 },
        missedGraceMinutes: { type: Number, default: 30, min: 5, max: 240 },
        queueState: { type: String, enum: ["open", "closed"], default: "open" },
        queueStateDate: { type: String, default: "", trim: true },
        queueOpenedAt: { type: Date, default: null },
        queueClosedAt: { type: Date, default: null },
        queueClosedReason: { type: String, default: "", trim: true, maxlength: 240 },
      },
      prescriptionTemplate: {
        title: { type: String, default: "Prescription", trim: true, maxlength: 80 },
        headerNote: { type: String, default: "", trim: true, maxlength: 180 },
        footerNote: { type: String, default: "Please follow the treating physician's instructions.", trim: true, maxlength: 240 },
        watermarkText: { type: String, default: "", trim: true, maxlength: 60 },
        showLogo: { type: Boolean, default: true },
        showClinicContact: { type: Boolean, default: true },
        showPatientId: { type: Boolean, default: true },
        showPatientAgeGender: { type: Boolean, default: true },
        showToken: { type: Boolean, default: true },
        showSymptoms: { type: Boolean, default: true },
        showDiagnosis: { type: Boolean, default: true },
        showTests: { type: Boolean, default: true },
        showAdvice: { type: Boolean, default: true },
        showFollowUp: { type: Boolean, default: true },
        showDoctorRegistration: { type: Boolean, default: true },
        showSignatureLine: { type: Boolean, default: true },
        watermarkEnabled: { type: Boolean, default: true },
      },
    },
    subscription: {
      billingMode: { type: String, enum: ["manual"], default: "manual" },
      status: {
        type: String,
        enum: ["unmanaged", "active", "expired", "suspended"],
        default: "unmanaged",
        index: true,
      },
      startsAt: { type: Date, default: null },
      endsAt: { type: Date, default: null, index: true },
      lastPaymentAt: { type: Date, default: null },
      lastRenewedAt: { type: Date, default: null },
      expiredAt: { type: Date, default: null },
      paymentNote: { type: String, default: "", trim: true, maxlength: 300 },
    },
    onboarding: {
      policyAcceptance: {
        type: new mongoose.Schema({
          termsVersion: { type: String, required: true, maxlength: 20 },
          privacyVersion: { type: String, required: true, maxlength: 20 },
          language: { type: String, enum: ["en", "hi"], required: true },
          acceptedAt: { type: Date, required: true },
        }, { _id: false }),
        default: undefined,
      },
      ownerName: { type: String, default: "", trim: true, maxlength: 100 },
      adminEmail: { type: String, default: "", lowercase: true, trim: true },
      submittedAt: { type: Date, default: Date.now },
      reviewedAt: { type: Date, default: null },
      reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "SuperAdmin", default: null },
      rejectionReason: { type: String, default: "", trim: true, maxlength: 500 },
    },
  },
  { timestamps: true }
);

export default mongoose.model("Tenant", tenantSchema);
